package elo7challenge.transfersystem.db;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

import elo7challenge.transfersystem.dao.DAOException;

public class DBTransferSetup {
	// XXX this class knows too much DDL sql, this should be improved

	private Connection connection;
	
	public DBTransferSetup(Connection connection) {
		this.connection = connection;
	}
	
	public void execute() throws DAOException {
		try {
			PreparedStatement prepareStatement = connection.prepareStatement("CREATE TABLE financial_transfer ("
					+ "id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1), "
					+ "sender_account VARCHAR(10), "
					+ "recipient_account VARCHAR(10), "
					+ "value NUMERIC(15,2),"
					+ "tax NUMERIC(15,2),"
					+ "scheduled_date DATETIME,"
					+ "type VARCHAR(1))");
			
			prepareStatement.execute();
			
		} catch (SQLException e) {
			throw new DAOException(e);
		}
	}
	
}
